// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGisoeVzn-3O1E0j8lEwyHACtTF_FfJI',
    appId: '1:261354147399:android:add059a0cecefedc166b62',
    messagingSenderId: '261354147399',
    projectId: 'seminar-five',
    databaseURL: 'https://seminar-five-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seminar-five.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0NdpdK79WO3Rynv5bw6z7lNU9C6x7Vc',
    appId: '1:261354147399:ios:3f916a58442275a7166b62',
    messagingSenderId: '261354147399',
    projectId: 'seminar-five',
    databaseURL: 'https://seminar-five-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seminar-five.appspot.com',
    iosClientId: '261354147399-s7k9koqee41vqqv1s5fl7sk8uv2j81br.apps.googleusercontent.com',
    iosBundleId: 'com.example.five',
  );
}
